name: code_text_field
description: A customizable code field supporting syntax highlighting, bi-directionnal scrolling and code modifiers
version: 1.0.2+1
homepage: https://github.com/BertrandBev/code_field
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.26.0"

dependencies:
  flutter:
    sdk: flutter
  linked_scroll_controller: ^0.2.0-nullsafety.0
  highlight:
    git:
      url: git@github.com:nank1ro/highlight.dart
      ref: v0.7.2
      path: packages/highlight
  flutter_highlight:
    git:
      url: git@github.com:nank1ro/highlight.dart
      ref: v0.7.2
      path: packages/flutter_highlight

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
